server:
  port: 8082
spring:
  application:
    name: Order-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#Eureka discovery client config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#the below swagger config is not needed
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html